import { NavLinksProps, Trip } from "./types";
import { IoChatbubbleEllipsesOutline } from "react-icons/io5";
import { PiAirplaneInFlight } from "react-icons/pi";

export const navLinks: NavLinksProps[] = [
  {
    title: "Chat",
    link: "/chat",
    icon: <IoChatbubbleEllipsesOutline size={14} />,
  },
  {
    title: "Suggestions",
    link: "/suggestions",
    icon: <PiAirplaneInFlight size={14} />,
  },
];

export const trips: Trip[] = [
  {
    id: 1,
    title: "Timgad Explorer",
    description:
      "Discover the Roman ruins of Timgad with a guided tour and cultural immersion.",
    TotalPriceDZD: 25000,
    steps: [
      {
        activity: "Arrival and Hotel Check-in",
        description: "Arrive at Batna and check into a cozy 3-star hotel.",
        PriceDZD: "7000",
        date: "2025-07-01",
        daysSpan: "Day 1",
      },
      {
        activity: "Timgad Ruins Tour",
        description:
          "Full-day exploration of the Timgad UNESCO World Heritage Site.",
        PriceDZD: "10000",
        date: "2025-07-02",
        daysSpan: "Day 2",
      },
      {
        activity: "Local Cuisine Experience",
        description: "Taste traditional dishes at a local restaurant.",
        PriceDZD: "3000",
        date: "2025-07-02",
        daysSpan: "Evening",
      },
      {
        activity: "Souvenir Shopping",
        description: "Buy authentic crafts from local markets.",
        PriceDZD: "5000",
        date: "2025-07-03",
        daysSpan: "Day 3",
      },
    ],
  },
  {
    id: 2,
    title: "Ghardaïa Oasis Adventure",
    description:
      "A mesmerizing journey through the M'zab Valley and Ghardaïa's ancient architecture.",
    TotalPriceDZD: 40000,
    steps: [
      {
        activity: "Flight to Ghardaïa",
        description: "Catch a domestic flight to Ghardaïa.",
        PriceDZD: "15000",
        date: "2025-08-10",
        daysSpan: "Day 1",
      },
      {
        activity: "Oasis Walk",
        description: "Guided tour through palm groves and traditional ksars.",
        PriceDZD: "10000",
        date: "2025-08-11",
        daysSpan: "Day 2",
      },
      {
        activity: "M'zab Cultural Experience",
        description: "Learn about Ibadi traditions and heritage.",
        PriceDZD: "5000",
        date: "2025-08-12",
        daysSpan: "Day 3",
      },
      {
        activity: "Handicraft Market",
        description: "Purchase handmade rugs and jewelry.",
        PriceDZD: "10000",
        date: "2025-08-13",
        daysSpan: "Day 4",
      },
    ],
  },
  {
    id: 3,
    title: "Tipaza Seaside Getaway",
    description: "Enjoy Mediterranean beaches and Roman ruins in Tipaza.",
    TotalPriceDZD: 28000,
    steps: [
      {
        activity: "Beach Day",
        description: "Relax at Chenoua beach.",
        PriceDZD: "5000",
        date: "2025-07-05",
        daysSpan: "Day 1",
      },
      {
        activity: "Tipaza Ruins Tour",
        description: "Guided tour of Roman ruins by the sea.",
        PriceDZD: "10000",
        date: "2025-07-06",
        daysSpan: "Day 2",
      },
      {
        activity: "Seafood Dining",
        description: "Dine at a seaside restaurant.",
        PriceDZD: "5000",
        date: "2025-07-06",
        daysSpan: "Evening",
      },
      {
        activity: "Local Market Shopping",
        description: "Buy crafts and souvenirs.",
        PriceDZD: "8000",
        date: "2025-07-07",
        daysSpan: "Day 3",
      },
    ],
  },
  {
    id: 4,
    title: "Hoggar Mountains Expedition",
    description: "Trekking adventure in the magical Hoggar mountains.",
    TotalPriceDZD: 55000,
    steps: [
      {
        activity: "Flight to Tamanrasset",
        description: "Arrive at Tamanrasset for the expedition.",
        PriceDZD: "20000",
        date: "2025-09-15",
        daysSpan: "Day 1",
      },
      {
        activity: "Assekrem Sunrise Trek",
        description: "Early morning trek to Assekrem Hermitage.",
        PriceDZD: "15000",
        date: "2025-09-16",
        daysSpan: "Day 2",
      },
      {
        activity: "Cultural Camp Night",
        description: "Spend a night under the desert stars.",
        PriceDZD: "10000",
        date: "2025-09-16",
        daysSpan: "Night",
      },
      {
        activity: "Market and Handicraft Tour",
        description: "Explore local artisan markets.",
        PriceDZD: "10000",
        date: "2025-09-17",
        daysSpan: "Day 3",
      },
    ],
  },
  {
    id: 5,
    title: "Algiers Cultural Weekend",
    description: "Short cultural immersion in the capital city.",
    TotalPriceDZD: 20000,
    steps: [
      {
        activity: "Casbah Tour",
        description: "Discover the historical Casbah of Algiers.",
        PriceDZD: "5000",
        date: "2025-06-20",
        daysSpan: "Day 1",
      },
      {
        activity: "Botanical Garden Visit",
        description: "Relax at Jardin d'Essai.",
        PriceDZD: "3000",
        date: "2025-06-21",
        daysSpan: "Morning",
      },
      {
        activity: "Museum of Antiquities",
        description: "Visit Algeria's national museum.",
        PriceDZD: "4000",
        date: "2025-06-21",
        daysSpan: "Afternoon",
      },
      {
        activity: "Seafront Dining",
        description: "Dinner at a restaurant overlooking the bay.",
        PriceDZD: "8000",
        date: "2025-06-21",
        daysSpan: "Evening",
      },
    ],
  },
  {
    id: 6,
    title: "Constantine Sky Bridges Tour",
    description: "Explore the stunning bridges and cliffs of Constantine.",
    TotalPriceDZD: 30000,
    steps: [
      {
        activity: "Train Ride to Constantine",
        description: "Scenic train journey through the countryside.",
        PriceDZD: "7000",
        date: "2025-07-10",
        daysSpan: "Day 1",
      },
      {
        activity: "Bridge Walks",
        description: "Visit Sidi M'Cid and Mellah Slimane bridges.",
        PriceDZD: "8000",
        date: "2025-07-11",
        daysSpan: "Day 2",
      },
      {
        activity: "Traditional Dinner",
        description: "Enjoy Constantine's famous chakhchoukha.",
        PriceDZD: "5000",
        date: "2025-07-11",
        daysSpan: "Evening",
      },
      {
        activity: "Museum Tour",
        description: "Visit the Cirta Museum.",
        PriceDZD: "10000",
        date: "2025-07-12",
        daysSpan: "Day 3",
      },
    ],
  },
  {
    id: 7,
    title: "Djanet Sahara Discovery",
    description:
      "Adventure across the beautiful dunes and Tassili n'Ajjer National Park.",
    TotalPriceDZD: 65000,
    steps: [
      {
        activity: "Flight to Djanet",
        description: "Arrival and preparation for desert excursion.",
        PriceDZD: "25000",
        date: "2025-10-01",
        daysSpan: "Day 1",
      },
      {
        activity: "Jeep Safari",
        description: "Explore the Sahara in 4x4 vehicles.",
        PriceDZD: "15000",
        date: "2025-10-02",
        daysSpan: "Day 2",
      },
      {
        activity: "Rock Art Hike",
        description: "View ancient rock paintings.",
        PriceDZD: "10000",
        date: "2025-10-03",
        daysSpan: "Day 3",
      },
      {
        activity: "Desert Camping",
        description: "Spend a night under the Saharan stars.",
        PriceDZD: "15000",
        date: "2025-10-03",
        daysSpan: "Night",
      },
    ],
  },
  {
    id: 8,
    title: "Oran Music and Beach Festival",
    description: "Experience music, beaches, and vibrant nightlife.",
    TotalPriceDZD: 45000,
    steps: [
      {
        activity: "Road Trip to Oran",
        description: "Journey to the coastal city.",
        PriceDZD: "8000",
        date: "2025-07-15",
        daysSpan: "Day 1",
      },
      {
        activity: "Beach Party",
        description: "Enjoy the famous Oran beaches.",
        PriceDZD: "10000",
        date: "2025-07-16",
        daysSpan: "Day 2",
      },
      {
        activity: "Music Festival",
        description: "Attend a summer music festival.",
        PriceDZD: "15000",
        date: "2025-07-17",
        daysSpan: "Day 3",
      },
      {
        activity: "City Night Tour",
        description: "Explore Oran by night.",
        PriceDZD: "12000",
        date: "2025-07-17",
        daysSpan: "Night",
      },
    ],
  },
  {
    id: 9,
    title: "Sahara Camel Caravan",
    description: "Join a traditional camel caravan across the desert.",
    TotalPriceDZD: 48000,
    steps: [
      {
        activity: "Arrival at Timimoun",
        description: "Fly to Timimoun and prepare for the journey.",
        PriceDZD: "20000",
        date: "2025-11-05",
        daysSpan: "Day 1",
      },
      {
        activity: "Camel Trekking",
        description: "Two-day camel caravan trek.",
        PriceDZD: "15000",
        date: "2025-11-06",
        daysSpan: "Day 2-3",
      },
      {
        activity: "Traditional Bedouin Camp",
        description: "Experience nomadic hospitality.",
        PriceDZD: "8000",
        date: "2025-11-06",
        daysSpan: "Night",
      },
      {
        activity: "Return and Market Visit",
        description: "Shop in Timimoun's vibrant market.",
        PriceDZD: "5000",
        date: "2025-11-07",
        daysSpan: "Day 4",
      },
    ],
  },
  {
    id: 10,
    title: "Bejaia Coastal Hike",
    description: "Discover the lush coastline and mountains of Bejaia.",
    TotalPriceDZD: 32000,
    steps: [
      {
        activity: "Arrival at Bejaia",
        description: "Travel by car or bus.",
        PriceDZD: "5000",
        date: "2025-07-20",
        daysSpan: "Day 1",
      },
      {
        activity: "Gouraya National Park Hike",
        description: "Hike the park trails with stunning views.",
        PriceDZD: "8000",
        date: "2025-07-21",
        daysSpan: "Day 2",
      },
      {
        activity: "Beach Relaxation",
        description: "Spend a day at Sahel beach.",
        PriceDZD: "7000",
        date: "2025-07-22",
        daysSpan: "Day 3",
      },
      {
        activity: "Local Food Tour",
        description: "Taste Bejaia's best seafood dishes.",
        PriceDZD: "12000",
        date: "2025-07-22",
        daysSpan: "Evening",
      },
    ],
  },
  {
    id: 11,
    title: "Constantine Bridges and Culture",
    description: "Visit the city of suspended bridges and rich heritage.",
    TotalPriceDZD: 30000,
    steps: [
      {
        activity: "Suspended Bridges Tour",
        description: "Guided walk across Constantine's iconic bridges.",
        PriceDZD: "8000",
        date: "2025-08-01",
        daysSpan: "Day 1",
      },
      {
        activity: "Palace of Ahmed Bey Visit",
        description: "Tour the historic palace and gardens.",
        PriceDZD: "7000",
        date: "2025-08-02",
        daysSpan: "Day 2",
      },
      {
        activity: "Museum Day",
        description: "Explore local museums and cultural centers.",
        PriceDZD: "6000",
        date: "2025-08-03",
        daysSpan: "Day 3",
      },
      {
        activity: "Local Souk Shopping",
        description: "Experience Constantine's bustling markets.",
        PriceDZD: "9000",
        date: "2025-08-03",
        daysSpan: "Evening",
      },
    ],
  },
  {
    id: 12,
    title: "Oran Beach Festival",
    description: "Enjoy the vibrant music and beach festivals of Oran.",
    TotalPriceDZD: 32000,
    steps: [
      {
        activity: "Beach Concert",
        description: "Attend a live beach concert.",
        PriceDZD: "12000",
        date: "2025-07-10",
        daysSpan: "Day 1",
      },
      {
        activity: "Plage Les Andalouses",
        description: "Spend a day at the famous beach.",
        PriceDZD: "8000",
        date: "2025-07-11",
        daysSpan: "Day 2",
      },
      {
        activity: "Night Market",
        description: "Stroll through the vibrant night market.",
        PriceDZD: "7000",
        date: "2025-07-11",
        daysSpan: "Evening",
      },
      {
        activity: "City Tour",
        description: "Visit landmarks like Fort Santa Cruz.",
        PriceDZD: "5000",
        date: "2025-07-12",
        daysSpan: "Day 3",
      },
    ],
  },
  {
    id: 13,
    title: "Sahara Camel Caravan",
    description:
      "Experience a traditional camel caravan journey in the Sahara Desert.",
    TotalPriceDZD: 60000,
    steps: [
      {
        activity: "Caravan Departure",
        description: "Meet your guide and camel caravan.",
        PriceDZD: "15000",
        date: "2025-10-01",
        daysSpan: "Day 1",
      },
      {
        activity: "Desert Trekking",
        description: "Cross golden dunes on camelback.",
        PriceDZD: "25000",
        date: "2025-10-02",
        daysSpan: "Day 2",
      },
      {
        activity: "Nomadic Camp",
        description: "Overnight stay with nomadic families.",
        PriceDZD: "10000",
        date: "2025-10-02",
        daysSpan: "Night",
      },
      {
        activity: "Sunrise Ride",
        description: "Enjoy a sunrise camel ride.",
        PriceDZD: "10000",
        date: "2025-10-03",
        daysSpan: "Day 3",
      },
    ],
  },
  {
    id: 14,
    title: "Annaba Historic Discovery",
    description: "Visit ancient ruins and beautiful beaches of Annaba.",
    TotalPriceDZD: 27000,
    steps: [
      {
        activity: "Hippo Regius Ruins",
        description: "Explore ancient Roman ruins.",
        PriceDZD: "9000",
        date: "2025-07-20",
        daysSpan: "Day 1",
      },
      {
        activity: "Basilica of St. Augustine",
        description: "Tour the historic basilica.",
        PriceDZD: "6000",
        date: "2025-07-21",
        daysSpan: "Day 2",
      },
      {
        activity: "Annaba Beach",
        description: "Relax on the city's main beach.",
        PriceDZD: "8000",
        date: "2025-07-21",
        daysSpan: "Afternoon",
      },
      {
        activity: "Local Cuisine Night",
        description: "Dine at a traditional Annaba restaurant.",
        PriceDZD: "4000",
        date: "2025-07-21",
        daysSpan: "Evening",
      },
    ],
  },
  {
    id: 15,
    title: "Béjaïa Coastal Retreat",
    description: "Explore the stunning coastal city of Béjaïa.",
    TotalPriceDZD: 29000,
    steps: [
      {
        activity: "Yemma Gouraya National Park",
        description: "Hike in the breathtaking national park.",
        PriceDZD: "10000",
        date: "2025-08-05",
        daysSpan: "Day 1",
      },
      {
        activity: "Béjaïa Seafront",
        description: "Relax and stroll along the seafront.",
        PriceDZD: "7000",
        date: "2025-08-06",
        daysSpan: "Day 2",
      },
      {
        activity: "Cape Carbon Hike",
        description: "Adventure to one of Algeria's most scenic spots.",
        PriceDZD: "8000",
        date: "2025-08-07",
        daysSpan: "Day 3",
      },
      {
        activity: "Seafood Dinner",
        description: "Enjoy fresh seafood at a local restaurant.",
        PriceDZD: "4000",
        date: "2025-08-07",
        daysSpan: "Evening",
      },
    ],
  },
];
